# Generated by Django 4.1 on 2022-08-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('floor', models.IntegerField(default=0)),
                ('details', models.CharField(max_length=500)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.building')),
            ],
        ),
        migrations.CreateModel(
            name='ArtLocation',
            fields=[
                ('art_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='inventory.artitem')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.person')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.spot')),
            ],
            options={
                'unique_together': {('art_item', 'spot')},
            },
        ),
    ]
