# Generated by Django 4.1 on 2022-08-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artitem',
            name='photo',
            field=models.ImageField(null=True),
        ),
    ]
