# Generated by Django 4.1 on 2022-09-26 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_alter_artlocation_responsible_person_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtBorrowingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('art_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.artitem')),
                ('reqester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.spot')),
            ],
        ),
        migrations.AddField(
            model_name='artlocation',
            name='request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.artborrowingrequest'),
        ),
    ]
