# Generated by Django 4.1 on 2022-09-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_artborrowingrequest_artlocation_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='artborrowingrequest',
            name='request_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='artborrowingrequest',
            name='spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.spot'),
        ),
    ]
