# Generated by Django 4.1 on 2022-09-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_artborrowingrequest_request_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artborrowingrequest',
            old_name='reqester',
            new_name='requester',
        ),
    ]
