# Generated by Django 4.1 on 2022-09-29 13:49

from re import I
from django.db import migrations


class Migration(migrations.Migration):

    def allow_municipality_worker_to_remove_art_borrowing_access(apps, schema_editor):
        Group = apps.get_model('auth', 'Group')
        Permission = apps.get_model('auth', 'Permission')

        # Groups
        municipality_workers = Group.objects.get(name='municipality_workers')
        municipality_workers_permission = Permission.objects.get(codename='delete_artborrowingrequest')
        municipality_workers.permissions.add(municipality_workers_permission)
        municipality_workers.save()

    dependencies = [
        ('inventory', '0007_alter_artborrowingrequest_requester'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(allow_municipality_worker_to_remove_art_borrowing_access),
    ]
